# Generated by Django 2.1.7 on 2019-09-02 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Crop_Type', '0010_crop_crop_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crop',
            old_name='farmImage',
            new_name='CropImage',
        ),
    ]
