# Generated by Django 2.1.7 on 2019-09-02 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Crop_Type', '0011_auto_20190902_0919'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crop',
            old_name='CropImage',
            new_name='crop_image',
        ),
    ]
