# Generated by Django 2.1.7 on 2019-09-02 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Crop_Type', '0012_auto_20190902_0924'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crop',
            old_name='crop_image',
            new_name='cropImage',
        ),
    ]
