# Generated by Django 2.1.7 on 2019-09-02 09:45

import Crop_Type.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crop_Type', '0013_auto_20190902_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='cropImageAnnotated',
            field=models.ImageField(default='farm.jpg', upload_to=Crop_Type.models.image_upload_path_2),
        ),
    ]
